- hosts: jenkinses
  become: yes 
  become_user: root
  become_method: sudo
  vars:
    jenkins_version: "2.73.1"
    jenkins_hostname: "{{ inventory_hostname }}"
    jenkins_port: 8080
    jenkins_install_via: "apt"
    jenkins_jobs:
      - "Hello"
    jenkins_include_custom_files: true
    jenkins_custom_files:
      - src: "users/demo/config.xml"
        dest: "users/demo/config.xml"
    jenkins_home: /mnt/efs
    jenkins_config_owner: jenkins 
    jenkins_config_group: jenkins

  roles:
    - emmetog.jenkins

